### ISSUE TITLE
File naming convention?

### ISSUE THREAD

**Issue by Numenter** [letsgamedev/Suffragium#35]
**How do you like your files, Sir?**
It's important to have consistency in “bigger” projects. (Especially in open source projects.)
Code style, folder structure and focus of this issue: **file names**.

Do we want to force a file naming convention?
What are your thoughts?

**Comment by Numenter** [comment]
Vote: Same but different. Each file type has its own naming convention.

**Comment by Numenter** [comment]
Vote: One to rule them all. All files are in snake_case. (or an other convention)

**Comment by Numenter** [comment]
Vote: Wild West. Everybody uses his own style.

**Comment by RedstoneMedia** [comment]
> Vote: Same but different. Each file type has its own naming convention.

I would like to advocate for this method, since scene and script files will usually have the same name (except the file ending), if you use `snake_case` for everything. \
Using `PascalCase` for Scenes and `snake_case` for script files does not have this problem and makes it easier to navigate to the correct file, especially if using third party code editors like VS Code. (*I can't tell you how often I anciently opened up a scene in VS Code when I really wanted to open up a script file*)

**Comment by Numenter** [comment]
Hiding specific files is an option.
https://stackoverflow.com/a/30142299

**Comment by RedstoneMedia** [comment]
Well, editing `.tscn` files in VS Code is a not so uncommon thing to do (especially to fix import or external resource issues). Going into the settings for that every time is also not an option.

**Comment by Numenter** [comment]
I can't remember if I ever edit a .tscn manually. I use just the godot editor, maybe that's why.
VS Code shows file extensions too, right?

In the end, it's only important that we all use the same naming convention.
