### ISSUE TITLE
Bug: Snake: Gameover when changing direction to fast

### ISSUE THREAD

**Issue by Numenter** [letsgamedev/Suffragium#66]
# Description
- [x] Bug Report

Gameover when changing direction to fast.
![snake_fast_rotation_death](https://user-images.githubusercontent.com/84922125/177206906-8aef7a7f-19fe-4029-bbad-681cf995c4d3.gif)

## Steps to reproduce the issue
1. Open Snake
2. Collect at least one apple
3. Move right
4. Press fast up or down than left

**Comment by b7g** [comment]
Thanks for opening the issue.

The underlying  issue is this: the direction is changed with the first press and again with the second press.
So that, the snake runs into itself backwards.
This is possible, because both direction changes are accepted, but no step/movement happened between them.

I came up with following solutions:
- discard direction changes when it was already changed once, until a step is done (probably would feel bad)
- queue the direction changes and apply them after the next step/movement was done (probably would feel better)

I don’t think both are ideal, but considering the speed of the game the second option could work very good.
Other opinions?

**Comment by MarioLiebisch** [comment]
Wanted to change something different anyway, so will have a PR for this soon™, so you can try it.
I think best strategy would be a middle way between both.🙂

**Comment by MarioLiebisch** [comment]
This should have been fixed by #70.
